#!/bin/bash
#
# Swift monitoring script for Nagios
#
# Copyright © 2012 eNovance <licensing@enovance.com>
#
# Author: Julien Danjou <julien@danjou.info>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

usage ()
{
    echo "Usage: $0 [OPTIONS]"
    echo " -h               Get help"
    echo " -A <url>         URL for obtaining an auth token"
    echo " -U <username>    Username to use to get an auth token"
    echo " -K <key>         Password to use ro get an auth token"
    echo " -T <tenantname>  Name of the tenant to list quotas"
    echo "                  (default: 1024)"
}

while getopts 'hH:A:U:K:T:' OPTION
do
    case $OPTION in
        h)
            usage
            exit 0
            ;;
        A)
            export OS_AUTH_URL=$OPTARG
            ;;
        U)
            export OS_USERNAME=$OPTARG
            ;;
        K)
            export OS_PASSWORD=$OPTARG
            ;;
        T)
            export OS_TENANT_NAME=$OPTARG
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

if ! which cinder >/dev/null 2>&1
then
    echo "cinder command not found"
    exit $STATE_UNKNOWN
fi

if ! cinder --os-tenant-name "$OS_TENANT_NAME" --os-username "$OS_USERNAME" --os-password "$OS_PASSWORD" --os-auth-url "$OS_AUTH_URL" quota-show "$OS_TENANT_NAME"  >/dev/null 2>&1
then
    echo "Unable to list default quotas"
    exit $STATE_CRITICAL
fi

echo "Successfully listed quotas from cinder API"
